name: Build manual macos zip

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Build manual MacOS'
  push:
    branches:
      - feature/gh-mac

env:
  QT_SELECT: 5
  QT_VERSION: '5.15.2' # quotes required or YAML parser will interpret as float

# The tag name is Test-macos-manual-YYmmdd-HHMM to enable multiple tests per day
jobs:

  macos:
    runs-on: macos-10.15

    steps:

      - name: checkout code
        uses: actions/checkout@v2.3.5

      - name: install qt
        uses: jurplel/install-qt-action@v2.14.0
        with:
          version: ${{ env.QT_VERSION }}

      - name: make Seamly2D for macos
        run: |
          xcode-select -s /Applications/Xcode_10.3.app/
          # Show MacOSX SDK Path
          xcrun -sdk macosx --show-sdk-path
          qmake Seamly2D.pro -r CONFIG+=no_ccache CONFIG+=noDebugSymbols
          make -j4

      - name: build dmg packages
        run: |
          hdiutil create -fs HFS+ -srcfolder src/app/seamly2d/bin/Seamly2D.app -volname "Seamly2D" Seamly2D.dmg
          hdiutil create -fs HFS+ -srcfolder src/app/seamlyme/bin/seamlyme.app -volname "SeamlyME" SeamlyME.dmg

      - name: pack package files into .zip
        run: |
          zip Seamly2D-macos.zip Seamly2D.dmg SeamlyME.dmg

      - uses: shallwefootball/s3-upload-action@master
        name: Upload S3
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY}}
          aws_bucket: github-31241
          source_dir: './Seamly2D-macos.zip'
